apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
spec:
  resources:
    inputs:
    - name: repo
      type: git
  steps:
  - name: run-test
    image: golang:1.16-alpine
    workingDir: /workspace/repo
    command: ["go"]
    args: ["test"]
    env:
      - name: "GOPROXY"
        value: "https://goproxy.cn,direct"